version: '3.8'
services:
  database:
    image: mysql:8.0
    container_name: rm_system_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rm_system
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    container_name: rm_system_adminer
    ports:
      - "8080:8080"
